ajndkr/lanarky

- fastapi_async_langchain/response.py
Fixes #3
- 🐛 fix LLM callback handlers
- 🐛 fix error handling inside `LangchainStreamingResponse`
> fix(response): prevent app from crashing on second message

- demo/app.py
- fastapi_async_langchain/response.py
This PR adds support to run a background task with the LLM chain output. This is useful for any after-response operations such as updating a database, running additional code conditioned on chain output, etc.
- ⚡ updated `LangchainStreamingResponse` to convert `background` attribute into a partial if `chain.arun` is successful
> feat: add support to run background task with chain output

- fastapi_async_langchain/responses/base.py
Fixes #27 
- 🐛 fixed error handling in `BaseLangchainStreamingResponse`
> fix(response): pass `BaseLangchainStreamingResponse` exception output to background task as `"outputs"`

- CONTRIBUTING.md
- fastapi_async_langchain/testing/gradio.py
- pyproject.toml
Changed the Gradio query function to include keep-alive, catch various errors and specify a smaller chunk_size.
In the previous version, streaming content via Gradio always "stalled" for me and was interrupted (in contrast to the web-socket pure FastAPI version).
With this fix I didn't see any interruptions with the gradio version anymore and the complete answer is always streamed.
(I also added seperate dev dependencies from the pre-commits to the pyproject.toml file, feel free to remove this part if you don't want it for whatever reason).
> Fix Gradio Streaming problems

- .github/workflows/code-check.yaml
- README.md
- fastapi_async_langchain/__init__.py
`fastapi-async-langchain` is now `lanarky`. This PR adds a small deprecation warning for users to install `lanarky` for future releases.
- 💡 added deprecation warning to package
- 📝 updated README
> chore: add deprecation warning

- .vscode/launch.json
- docs/features.rst
- examples/README.md
- examples/app/zero_shot_agent.py
- examples/requirements.in
- examples/requirements.txt
- lanarky/callbacks/__init__.py
- lanarky/callbacks/agents.py
- lanarky/responses/streaming.py
- lanarky/websockets/base.py
- tests/callbacks/test_agents.py
Closes #53.
This PR adds support for langchain agents. 🚀 
- ✨ add streaming and websocket callback handlers for `AgentExecutor` class types
- 🔨 added zero shot agent example
- 📝 updated examples README
- ⚡ added `callback_kwargs` for responses and websocket connections
- ✅ added new unit tests
> feat: Add callback handlers for Langchain agents

- .github/workflows/ci.yaml
- lanarky/callbacks/base.py
When going from `v0.6.2 -> v0.6.3` the following error started occurring on every new streamed token:
`Error in on_llm_new_token callback: sequence item 1: expected a bytes-like object, str found`
This happens for both regular chains and new agents as tested by multiple examples and a private app which uses lanarky.
This fix solves this by encoding the message body to utf-8.
- encode message body to utf-8
> fix `StreamingResponse` message content encoding

- README.md
- docs/getting_started.rst
- docs/langchain/deploy.rst
- lanarky/routing/langchain.py
- lanarky/routing/utils.py
- tests/routing/test_langchain_router.py
This pull request introduces two new methods to the `LangchainRouter` class:
- `add_langchain_api_route`: This method allows the addition of API routes to the router, supporting multiple langchain objects.
- `add_langchain_api_websocket_route`: This method enables the addition of websocket routes to the router, accommodating multiple langchain objects.
- ✨ added new methods to `LangchainRouter`
- ✅ updated unit tests
> feat: add new methods to `LangchainRouter`

- README.md
- docs/getting_started.rst
- docs/langchain/deploy.rst
- examples/README.md
- examples/app/conversation_chain.py
- examples/app/retrieval_qa_w_sources.py
- examples/app/zero_shot_agent.py
- examples/requirements.txt
- lanarky/routing/langchain.py
- lanarky/routing/utils.py
- tests/routing/test_langchain_router.py
This PR adds a `name_prefix` parameter when creating dynamic request and response models to avoid class name clash when 2 or more langchain routes are added.
- ✨ added `name_prefix` param
- ✏️ fixed docs
- 🔨 updated demo examples
> fix: add `name_prefix` for creating dynamic request and response models

- lanarky/websockets/base.py
Orginally did this do update what is below to log at the debug level instead of info as it was creating an excessive amount of logs in our application. I see that you've already done that though :)
```python
openai.aiosession.set(aiohttp.ClientSession())
logger.info(f"opeanai.aiosession set: {openai.aiosession.get()}")
try:
await func(*args, **kwargs)
finally:
await openai.aiosession.get().close()
logger.info(f"opeanai.aiosession closed: {openai.aiosession.get()}")
```
> ♻️ Change from logger info to debug.

- lanarky/websockets/base.py
- tests/conftest.py
- tests/websockets/test_websocket_connection.py
This pull request introduces a new feature that allows the `connect()` method in the WebsocketConnection class to control whether to accept the WebSocket connection or not. 
This is done by adding a new parameter `accept_connection` to the `connect() `method. By default, this parameter is set to `True`, meaning the WebSocket connection will be accepted when the `connect()` method is called. 
However, if `accept_connection` is set to `False`, the `connect()` method will not attempt to accept the WebSocket connection. 
This feature is particularly useful in scenarios where the first message from the client after establishing the WebSocket connection is used for authentication purposes.
Fixes #86
Added a new parameter accept_connection to the connect() method in the WebsocketConnection …
> feat: Add option to accept or not accept WebSocket connection

- lanarky/responses/streaming.py
- lanarky/websockets/base.py
- pyproject.toml
This PR adds a new parameter to the `from_chain` classmethod of `StreamingResponse` and `WebsocketConnection`: `callback`
`callback` param will allow users to pass custom callback handlers instead of registering them as mentioned in the docs: https://lanarky.readthedocs.io/en/latest/langchain/custom_callbacks.html
- ✨ added `callback` param to `StreamingResponse` and `WebsocketConnection`
> feat: allow users to pass custom callback handler

- .gitignore
- lanarky/callbacks/base.py
- lanarky/callbacks/llm.py
- lanarky/callbacks/retrieval_qa.py
- lanarky/schemas/__init__.py
- lanarky/schemas/callbacks.py
- tests/callbacks/test_retrieval_qa.py
Async streaming callbacks were not returning the final answer when langchain.llm_cache was set, and not streaming tokens because the answer was cached.  This PR fixes the issue and updates some tests to check when caching is enabled, that the answer is returned by the callbacks.
Fixes #133
* Fixed Async callback handling when streaming and cache is enabled to return final answer.
* Added settings.json and .flake8 config to .gitignore.
* Updated BaseRetrievalQAStreamingJSONResponse to not inherit from StreamingJSONResponse, because it adds an extra empty token to the output for no reason.
* Added AnswerStreamingJSONResponse to add answer to the output.
* Added llm_cache_enabled and llm_cache_used properties to AsycLanarkyCallback.
> fix: return final answer when streaming and cache is enabled

- lanarky/routing/utils.py
Add "LLMChain" to BASE_LANGCHAIN_TYPES
Fixes # (issue)
-
> fix: add missing `LLMChain` type for langchain router

- pyproject.toml
Updates `typing-extensions` to be compatible with `Pydantic V2`. V2 requires at least `4.6.1`, added `4.7.1`, as that seems to be installed with `Pydantic 2.3.0`.
Fixes #123 
- Upgrade `typing-extensions` from `4.5.0` to `4.7.1`
> chore(deps): update `typing-extensions` to be compatible with Pydantic V2

- README.md
- lanarky/callbacks/agents.py
- lanarky/callbacks/base.py
- lanarky/callbacks/retrieval_qa.py
- lanarky/responses/streaming.py
- lanarky/routing/utils.py
- lanarky/schemas/websockets.py
- lanarky/testing/settings.py
- lanarky/websockets/base.py
- poetry.lock
- pyproject.toml
- tests/callbacks/test_retrieval_qa.py
- tests/responses/test_streaming.py
- tests/routing/test_langchain_router.py
- tests/websockets/test_websocket_connection.py
Fixes #148 
Fixes #141 
Fixes #110
- ⬆️ bumped pydantic and openai dependencies
- ♻️ migrated codebase to pydantic_v2
- ✅ fixed breaking unit tests
- ➕ added uvicorn as dev dependency (useful for running test applications)
- 🔥 removed `openai_aiosession` decorator from `StreamingResponse` (redundant after openai_v1 migration)
- 🔥 removed pydantic dependency from callback handler classes (langchain doesn't use pyndantic for the native handlers)
> build(deps): bump pydantic and openai dependencies

- lanarky/callbacks/base.py
- lanarky/responses/streaming.py
- poetry.lock
- pyproject.toml
- tests/responses/test_streaming.py
Fixes #121
Fixes #112
This PR adds the [`EventSource` protocol](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#interfaces) for streaming LLM output. We still respect the text and JSON streaming modes but all events will now stream as follows:
```
data: <llm_token_1>
data: <llm_token_2>
```
This also allows the possibility of implementing named events for special use cases:
```
event: <event_a>
data: <llm_token_1>
event: <event_b>
data: <llm_token_2>
```
Finally, the StreamingResponse also improves error handling by sending a 500 error event when chain execution fails (Fixes #146)
- ➕ added `sse-starlette` dependency
- ♻️ refactored `StreamingResponse` class and base callback handlers
> feat(core): add `EventSource` protocol

- README.pypi.md
- lanarky/adapters/langchain/callbacks.py
- lanarky/adapters/langchain/dependencies.py
- lanarky/adapters/langchain/utils.py
- lanarky/adapters/openai/dependencies.py
- lanarky/adapters/openai/resources.py
- lanarky/adapters/openai/utils.py
- lanarky/utils.py
- pyproject.toml
With v0.8 release, lanarky primarily only supported pydantic 2.0+ users. This PR adds support for v1 users as well.
- ⚡ added new util functions to handle multiple pydantic versions
- ⚡ updated adapter modules
- 📝 added new PyPI friendly README
> fix: add support for pydantic v1 users

- docs/learn/adapters/langchain/callbacks.md
- lanarky/adapters/langchain/responses.py
- pyproject.toml
Fixes #164.
This PR adds new functionality to langchain adapter's streaming response: run mode.
Setting the run mode to "async" or "sync" defines how the langchain object is executed (via `.acall` or `__call__` respectively)
- ✨ added `run_mode` attribute to `StreamingResponse`
- 📝 updated docs to create custom callback handlers
> fix(langchain): add support for LLMs without support for async callback handlers

- lanarky/adapters/langchain/callbacks.py
- lanarky/adapters/langchain/responses.py
- lanarky/events.py
- lanarky/responses.py
- lanarky/utils.py
- lanarky/websockets.py
- pyproject.toml
The `(str, Enum)` enum classes don't work as expected for python 3.11 due to the presence of `StrEnum` class from `enum` library.
- ⚡ added `StrEnum` definition in utils
- ⚡ updated all enum classes
> fix: update all enum classes to support python 3.11+ users

- poetry.lock
- pyproject.toml
This PR updates the langchain dependency constraint to allow all langchain versions <0.1
- 🔧 updated poetry.lock
- ⬆️ bumped version
> build(deps): update langchain dependency constraint

- .gitignore
- .pre-commit-config.yaml
- lanarky/adapters/langchain/callbacks.py
- poetry.lock
- pyproject.toml
This PR attempts to resolve #186 
The issue occurs when streaming with `ChatVertexAI` in "sync" run mode.
- ⬆️ upgraded dependencies and pre-commit hooks
- ⚡ added missing `on_chat_model_start` method
> fix: add missing callback method to base callback handler class
